include ../../global.mk

SOURCE = $(wildcard PKGMETA/*.cpp) $(wildcard DWLOG/*.cpp) 
OBJ = $(patsubst %.cpp,%.o,$(SOURCE))

PKGMETA/%.o : PKGMETA/%.cpp
	@$(CXX) $(CXXFLAGS) -DTSF4G_TDR_DEBUG -c -o $@ $< -I./
	@echo [CXX] $@

DWLOG/%.o : DWLOG/%.cpp
	@$(CXX) $(CXXFLAGS) -DTSF4G_TDR_DEBUG -c -o $@ $< -I./
	@echo [CXX] $@

all:$(OBJ)
	$(AR) q ../$(COMM_LIB_FILE) $(OBJ)

.PHONY: clean

clean:
	rm -f $(OBJ)
	rm -rf PKGMETA
	rm -rf DWLOG

