CREATE DATABASE IF NOT EXISTS `DWLog` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `CltFightStats` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `PVEStats` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `PlayerDataStats` DEFAULT CHARACTER SET utf8mb4;